v2v-helper/migrate/migrate.go
v2v-helper/migrate/migrate_test.go

Mount 1 disk at a time per VM

---

v2v-helper/migrate/migrate.go
v2v-helper/migrate/migrate_test.go
v2v-helper/nbd/nbdops.go
v2v-helper/nbd/nbdops_mock.go
v2v-helper/openstack/openstackops.go
v2v-helper/reporter/reporter.go
v2v-helper/vcenter/vcenterops_test.go
v2v-helper/virtv2v/virtv2vops.go
v2v-helper/virtv2v/virtv2vops_mock.go

Also contains fix for https://issues.redhat.com/browse/RHEL-54377
Parallelized incremental copy

Fix for Centos and Rocky VMs

---

deploy/04ui.yaml
ui/Dockerfile
ui/package-lock.json
ui/package.json
ui/src/api/ApiClient.ts
ui/startup.sh
ui/vite.config.ts
ui/yarn.lock

Dynamically fetch the k8s API token from the pod

UI: Fetch the k8s API token from the pod

---

k8s/migration/internal/controller/migrationplan_controller.go

Add missing errors to log output

Support for VMs with capital names

---

k8s/kube-prometheus/manifests/alertmanager-alertmanager.yaml
k8s/kube-prometheus/manifests/grafana-config.yaml
k8s/kube-prometheus/manifests/grafana-deployment.yaml
k8s/kube-prometheus/manifests/prometheus-prometheus.yaml
ui/deploy/ui.yaml

Can now access the grafana UI at `https://<IP>/grafana`

Use HTTPS for grafana

---

v2v-helper/vm/vmops.go

https://issues.redhat.com/browse/CNV-51521
Ref: https://github.com/kubevirt/containerized-data-importer/pull/3534

Fix for incomplete transfer of changed blocks

---

ui/src/components/grid/CustomSearchToolbar.tsx
ui/src/features/migration/MigrationForm.tsx
ui/src/features/migration/VmsSelectionStep.tsx
ui/tsconfig.json

Changes:- 
1. Displayed additional VM details like `Status`, `Current IP`, `Network Interface(s)`, `OS`.
2. Sorted VMs list by default to show `Running` VMs on top.
3. Added a Refresh button on VMs list to allow manual refresh.
4. Disabled selection for VMs with `Stopped` Status, and provided a tooltip saying "Turn on the VM to enable migration."
https://github.com/user-attachments/assets/69c51b18-3598-4af1-af83-f412346d811d
b-fe2aee570f08

106 - check if the source vm has an ip if it does not ask the user if DHCP is okay

---

.github/workflows/packer.yml
Makefile
k8s/migration/internal/controller/migrationplan_controller.go
v2v-helper/Dockerfile
v2v-helper/migrate/migrate.go
v2v-helper/migrate/migrate_test.go
v2v-helper/openstack/openstackops.go
v2v-helper/utils/constants.go
v2v-helper/virtv2v/virtv2vops.go
v2v-helper/vm/vmops.go

This PR:
check if disks have os installed in lexical order

check if disks have os installed in lexical order (release)

---

ui/src/api/migration-plans/migrationPlans.ts
ui/src/api/migrations/model.ts
ui/src/features/migration/MigrationForm.tsx
ui/src/features/migration/VmsSelectionStep.tsx
ui/src/pages/dashboard/Dashboard.tsx
ui/src/pages/dashboard/MigrationProgress.tsx
ui/src/pages/dashboard/MigrationProgressWithPopover.tsx

1. Added a Detailed Migration Progress Message also showing the data copy progress and other phases.
2. In the Migration Form, disabled the already migrated vms from selection from further migration.
Also removed the popover from Migration progress for now since it was conveying incorrect progress messages.
Fixed #115 and #128

Data Copy Progress

---

deploy/00crds.yaml
k8s/migration/api/v1alpha1/migration_types.go
k8s/migration/api/v1alpha1/vjailbreaknode_types.go
k8s/migration/cmd/main.go
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_vjailbreaknodes.yaml
k8s/migration/config/manager/kustomization.yaml
k8s/migration/config/manager/manager.yaml
k8s/migration/internal/controller/migration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/vjailbreaknode_controller.go
k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go

Api changes for UI 

---

k8s/migration/api/v1alpha1/migration_types.go
k8s/migration/internal/controller/migration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/vjailbreaknode_controller.go
k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/migrationutils.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go

status fixes for migration phases

---

k8s/migration/go.mod
k8s/migration/go.sum
k8s/migration/internal/controller/migration_controller.go
v2v-helper/migrate/migrate.go

fix failed migration phase

---

ui/src/App.tsx
ui/src/pages/dashboard/Dashboard.tsx

UI fix to navigate to dashboard if nodes are not empty.

---

v2v-helper/migrate/migrate.go

better error logging for v2v-helper pod

---

deploy/00crds.yaml
k8s/migration/config/rbac/role.yaml
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/vjailbreaknode_controller.go
k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go

Private/release v0.1.4/omkard/cleanup nodes

---

k8s/migration/internal/controller/vjailbreaknode_controller.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go

Change active migration function

---

k8s/migration/internal/controller/vmwarecreds_controller.go

fix vmwarecreds npe

---

k8s/migration/internal/controller/vmwarecreds_controller.go

add debug log

---

image_builder/vjailbreak-image.pkr.hcl
ui/src/api/nodes/model.ts
ui/src/api/nodes/nodeMappings.ts
ui/src/pages/dashboard/NodesTable.tsx
ui/src/pages/dashboard/ScaleUpDrawer.tsx

Fix flavour and remove activemigrations 

---

ui/src/api/nodes/model.ts
ui/src/pages/dashboard/ScaleUpDrawer.tsx

Spelling issue Fix 

---

README.md

add note to get worker password

---

k8s/migration/internal/controller/openstackcreds_controller.go
k8s/migration/internal/controller/vjailbreaknode_controller.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go

fix agent loop

---

README.md

update oras pull image tag to 'v0.1.4'

---

templates/functional_Specification.md

Adding templates for github wiki

---

README.md
deploy/00crds.yaml
k8s/migration/config/manager/kustomization.yaml

update image tag to v0.1.5

---

.github/workflows/01_update_release_notes.yaml

Update checkout action to v4

---

.github/workflows/01_update_release_notes.yaml

Update checkout action to generate release notes

---

.github/workflows/01_update_release_notes.yaml

Update release action 2

---

.github/workflows/01_update_release_notes.yaml
docs/src/content/docs/index.mdx

Update the correct gh-pages

---

.github/workflows/01_update_release_notes.yaml
docs/src/content/docs/index.mdx

Update the correct version for gh-pages

---

ui/src/components/forms/OpenstackCredentialsForm.tsx
ui/src/components/forms/VmwareCredentialsForm.tsx
ui/src/utils.ts

- https://github.com/platform9/vjailbreak/issues/269
- Added validations for the VMware and OpenStack credential name fields.

Bug :: #269 :: Unable to use uppercase letters in a credential's name

---

.github/workflows/packer.yml
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/migrationtemplate_controller.go
k8s/migration/internal/controller/openstackcreds_controller.go
k8s/migration/pkg/utils/credutils.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go

fix insecure openstack authentication (release)

---

.github/workflows/packer.yml
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/migrationtemplate_controller.go
k8s/migration/internal/controller/openstackcreds_controller.go
k8s/migration/pkg/utils/credutils.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go
ui/src/api/helpers.ts
ui/src/api/secrets/secrets.ts
ui/src/components/forms/OpenstackCredentialsForm.tsx
ui/src/components/forms/VmwareCredentialsForm.tsx
ui/src/features/migration/MigrationForm.tsx
ui/src/pages/dashboard/ScaleUpDrawer.tsx
ui/src/utils.ts

( release ) UI improvements and Backend fixes. 

---

docs/src/content/docs/index.mdx

**What this PR does / why we need it**: Update the video link to lates YT video.
Fixes #

Update video link to latest

---

README.md

fix readme for openstackcreds and vmware creds

---

.github/workflows/packer.yml
image_builder/scripts/install.sh
image_builder/vjailbreak-image.pkr.hcl

( release ) Change base image to ubuntu base image, reduced image size. 

---

k8s/migration/internal/controller/migration_controller.go
k8s/migration/pkg/constants/constants.go

Ignore Failed phase on retry

---

deploy/00crds.yaml
k8s/migration/api/v1alpha1/migration_types.go
k8s/migration/api/v1alpha1/migrationplan_types.go
k8s/migration/api/v1alpha1/migrationtemplate_types.go
k8s/migration/api/v1alpha1/networkmapping_types.go
k8s/migration/api/v1alpha1/openstackcreds_types.go
k8s/migration/api/v1alpha1/storagemapping_types.go
k8s/migration/api/v1alpha1/vjailbreaknode_types.go
k8s/migration/api/v1alpha1/vmwarecreds_types.go
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_migrationplans.yaml
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_migrations.yaml
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_networkmappings.yaml
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_openstackcreds.yaml
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_storagemappings.yaml
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_vjailbreaknodes.yaml
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_vmwarecreds.yaml
k8s/migration/config/manager/kustomization.yaml
k8s/migration/internal/controller/migration_controller.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go

api cosmetic fixes

---

v2v-helper/migrate/migrate.go
v2v-helper/openstack/openstackops.go
v2v-helper/pkg/constants/constants.go
v2v-helper/pkg/utils/openstackopsutils.go

check VM status before marking migration as complete

---

ui/src/api/nodes/model.ts
ui/src/pages/dashboard/NodesTable.tsx

Fixes # 
This PR resolves UI inconsistencies by standardizing property naming across the codebase. It updates both data models and dashboard components for uniform naming, ensuring proper data retrieval and display. The update removes deprecated code and implements a functional active migrations column, enhancing reliability and consistency.
<br>
<br>
<br>
<br>
</div>

UI: Fix active migration

---

v2v-helper/migrate/migrate_test.go
v2v-helper/openstack/openstackops_mock.go
v2v-helper/virtv2v/virtv2vops_mock.go
v2v-helper/vm/vmops_mock.go

fix mocks, unit tests

---

ui/src/features/migration/VmsSelectionStep.tsx
ui/src/pages/dashboard/Dashboard.tsx
ui/src/pages/dashboard/ScaleUpDrawer.tsx

resolved lint issues

---

.github/workflows/packer.yml

Actions enhancement: Build and push on every PR raised to main or release branch. 

---

.github/workflows/01_update_release_notes.yaml
docs/src/components/githubRelease.astro
docs/src/content/docs/index.mdx

Fixes # 
This pull request resolves version inconsistencies by removing obsolete workflow lines and updating version references across multiple files. The changes include removing outdated YouTube variable assignments and streamlining GitHub workflow configuration while ensuring consistent version references to v0.1.6 throughout the repository.
<br>
<br>
<br>
<br>
</div>

Fix versions and github actions

---

.github/workflows/packer.yml
image_builder/configs/rsyncd.conf
image_builder/scripts/install.sh
image_builder/vjailbreak-image.pkr.hcl
k8s/migration/internal/controller/migrationplan_controller.go
v2v-helper/Makefile

v2v-helper build was failing due to libnbd not being found.
Fixes # 
This pull request resolves critical CGO linking issues causing build failures, introduces a new rsync configuration file, and refines installation scripts for the rsync daemon. It enhances image builder provisioning by updating file paths and command sequences while improving overall code clarity and maintainability.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>

Build: Fix CGO Linking for libnbd Library in Build Process (release)

---

.github/workflows/packer.yml

release: Fix github action when PR raised from release branch

---

docs/package.json

Add optional dependency 

---

docs/src/components/githubRelease.astro
docs/src/content/docs/index.mdx
docs/src/content/docs/introduction/getting_started.mdx
docs/src/content/docs/release_docs/v0.1.7.md

Fixes # 
This PR updates version references from v0.1.6 to v0.1.7 across multiple documentation files, including GitHub releases and markdown files. The changes ensure consistency in version information throughout the project documentation, enhancing clarity and accuracy for users.
<br>
<br>
<br>
<br>
</div>

Update release notes

---

README.md

Updating the video

---

docs/src/content/docs/guides/scaling.md
docs/src/content/docs/guides/troubleshooting.md
docs/src/content/docs/introduction/components.md
docs/src/content/docs/introduction/getting_started.mdx
k8s/migration/pkg/utils/migrationutils.go
ui/src/features/migration/NetworkAndStorageMappingStep.tsx

Adds commonly used troubleshooting steps & explanations. Marks the manual VDDK distribution as required for certain previous releases only. Updated "Openstack" to "OpenStack" in two places in the UI.
Fixes # 
This PR enhances documentation by removing outdated steps and clarifying instructions for vJailbreak and VDDK libraries. It also improves naming consistency by addressing the capitalization of 'OpenStack' throughout migration utilities and UI components, resulting in clearer documentation and more consistent codebase.
<br>
<br>
<b>Unit tests …

Damian doc updates

---

deploy/00crds.yaml
k8s/migration/api/v1alpha1/bmconfig_types.go
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_bmconfigs.yaml
k8s/migration/internal/controller/rollingmigrationplan_controller.go
pkg/vpwned/deploy/k8s.svc.yaml
ui/src/api/vmware-clusters/vmwareClusters.ts
ui/src/api/vmware-hosts/vmwareHosts.ts

UI integrations

---

k8s/migration/internal/controller/clustermigration_controller.go
k8s/migration/internal/controller/esximigration_controller.go
k8s/migration/internal/controller/openstackcreds_controller.go
k8s/migration/internal/controller/rollingmigrationplan_controller.go
k8s/migration/pkg/scripts/cloud-init.tmpl.yaml
k8s/migration/pkg/utils/bmprovisionerutils.go
k8s/migration/pkg/utils/rollingmigrationutils.go

k8s unique names, fix for cloud-init

---

v2v-helper/pkg/utils/openstackopsutils.go

Fixes #454 
This PR enhances the openstack operations utility by improving volume availability checking logic. It adds verification that volumes have no attachments in addition to having 'available' status. This change prevents potential race conditions during volume state evaluation, ensuring volumes are truly ready for use.
<br>
<br>
<br>
<br>
</div>

Wait for volume attachements also to clear out.

---

k8s/migration/api/v1alpha1/clustermigration_types.go
k8s/migration/api/v1alpha1/esximigration_types.go
k8s/migration/internal/controller/clustermigration_controller.go
k8s/migration/internal/controller/esximigration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/rollingmigrationplan_controller.go
k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/rollingmigrationutils.go

added ability to pause rolling migration plan

---

v2v-helper/vcenter/vcenterops.go

**What this PR does / why we need it**: Added RenameVM and MoveVMFolder methods to vcenterops.go for post-migration actions. 
This PR adds new post-migration capabilities to vcenterops.go with RenameVM and MoveVMFolder functions. These enhancements improve VM management within vCenter after migration, including renaming and relocation features. The implementation includes proper dependency updates and comprehensive error handling for reliable operation.
<br>
<br>
<br>
<br>
</div>

Add ons in v2v-helper for post-migration actions

---

image_builder/configs/daemonset.yaml
image_builder/configs/rsyncd.conf
k8s/migration/internal/controller/migrationplan_controller.go

Fixes # 
This pull request enhances log synchronization between worker and master nodes by adding rsync commands in the daemonset configuration. It modifies the rsyncd configuration for log path and permissions, improving overall log management and addressing previous configuration issues.
<br>
<br>
<br>
<br>
</div>

Sync migration logs from worker to master ( release )

---

k8s/migration/api/v1alpha1/esximigration_types.go
k8s/migration/internal/controller/clustermigration_controller.go
k8s/migration/internal/controller/esximigration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/openstackcreds_controller.go
k8s/migration/internal/controller/rollingmigrationplan_controller.go
k8s/migration/pkg/utils/credutils.go
k8s/migration/pkg/utils/rollingmigrationutils.go

vPwned: UI integration enhancements

---

k8s/migration/internal/controller/esximigration_controller.go
k8s/migration/internal/controller/migration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/rollingmigrationplan_controller.go
k8s/migration/internal/controller/vjailbreaknode_controller.go
k8s/migration/pkg/scripts/cloud-init.tmpl.yaml
k8s/migration/pkg/utils/rollingmigrationutils.go

migrationplan name fix

---

docs/astro.config.mjs
docs/src/content/docs/guides/debug_vjailbreak_install.md
docs/src/content/docs/guides/debuglogs.md
docs/src/content/docs/introduction/getting_started.mdx
docs/src/content/docs/introduction/prerequisites.md
k8s/migration/internal/controller/migrationplan_controller.go

Fixes #440 #475 
This PR enhances documentation by adding a new guide entry to astro configuration and updating Getting Started docs to remove outdated instructions. It also improves code maintainability by removing an unnecessary logging statement from the migration controller.
<br>
<br>
<br>
<br>
</div>

Document: Add cbt privilege and flavor selection logic in Doc. 

---

k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/openstackcreds_controller.go
k8s/migration/pkg/utils/credutils.go

Fixes # 
This PR fixes build issues by updating GetClosestFlavour function calls and removing unnecessary context parameters in migration plan and OpenStack credentials controllers. It also eliminates redundant logging in certificate utilities, improving code coherence and simplifying debugging information.
</div>

fix build issue. 

---

k8s/migration/internal/controller/migration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
v2v-helper/migrate/migrate.go

Fix normal migration status

---

deploy/00crds.yaml
k8s/migration/config/manager/kustomization.yaml
v2v-helper/pkg/utils/nbdutils.go

fix debug log file for migration re-runs

---

v2v-helper/migrate/migrate.go
v2v-helper/virtv2v/virtv2vops.go

Fixes # 
This PR enhances the logging mechanism in guest command execution modules by updating error messages to include trimmed command outputs. It improves error reporting across migration and guest operation files, providing better context in failure scenarios. These changes facilitate more effective troubleshooting by ensuring errors are reported with greater detail.
</div>

improved guestfish logging

---

ui/src/api/vmware-machines/vmwareMachines.ts
ui/src/features/migration/RollingMigrationForm.tsx
ui/src/features/migration/VmsSelectionStep.tsx

Fixes #
This pull request enhances VM migration functionality by introducing OS and flavor assignment capabilities with improved validations and UI updates. It extends the VMware machines API with an 'osFamily' property and refines the migration form interface with better error handling and state management. These changes deliver a more robust and user-friendly experience during migration configuration.
</div>

add/update/edit  os and flavors in vms list in rolling conversion

---

k8s/migration/internal/controller/openstackcreds_controller.go
k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/pcdutils.go
v2v-helper/pkg/constants/constants.go

fixes: #617 
This PR enhances PCD cluster management with improved logging, error handling, and standardized naming conventions. It implements a new deletion mechanism for null clusters and adds a dedicated function for removing invalid cluster entries. These changes refine dummy cluster handling processes and strengthen OpenStack credential management workflows, ensuring more stable operation of the cluster management features.
</div>

pcdclusters and tenant in UI (release)

---

ui/src/api/secrets/secrets.ts
ui/src/features/migration/MigrationForm.tsx
ui/src/features/migration/RollingMigrationForm.tsx
ui/src/features/migration/SourceDestinationClusterSelection.tsx
ui/src/features/migration/useClusterData.ts

Fixes # 
This pull request enhances the migration feature by adding a new getSecrets API function and improving migration forms and utility modules. The changes include adjustments to error handling, parameter management, and UI display that collectively streamline the migration workflow and improve usability.
</div>

Destination cluster dropdown changes for same id

---

.github/PULL_REQUEST_TEMPLATE.md

PR description for testing

---

.github/workflows/01_update_release_notes.yaml
.github/workflows/deploy_gh_page.yaml

Move the docs to be build from gh-pages
fixes #
This pull request updates GitHub workflow configurations to improve release note automation and documentation deployment. It adjusts event triggers and input defaults in the release notes workflow and refines key parameters in the deployment workflow. These changes ensure that release notes are processed correctly and that documentation builds from the appropriate branch.
</div>

Update docs from gh-pages

---

docs/src/content/docs/index.mdx
docs/src/content/docs/release_docs/v0.1.14.md
docs/src/content/docs/release_docs/v0.1.15.md

fixes #
This PR updates documentation configurations by restructuring the guide section in astro.config.mjs to enable autogeneration and adding an Archives section. It also updates the version reference in index.mdx from v0.1.12 to v0.1.15, enhancing overall documentation clarity and consistency.
</div>

Add latest docs

---

k8s/migration/Makefile
k8s/migration/api/v1alpha1/esximigration_types.go
k8s/migration/api/v1alpha1/openstackcreds_types.go
k8s/migration/api/v1alpha1/rollingmigrationplan_types.go
k8s/migration/cmd/main.go
k8s/migration/internal/controller/bmconfig_controller_test.go
k8s/migration/internal/controller/clustermigration_controller.go
k8s/migration/internal/controller/clustermigration_controller_test.go
k8s/migration/internal/controller/esximigration_controller.go
k8s/migration/internal/controller/esximigration_controller_test.go
k8s/migration/internal/controller/rollingmigrationplan_controller.go
k8s/migration/internal/controller/rollingmigrationplan_controller_test.go
k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/bmprovisionerutils.go
k8s/migration/pkg/utils/credutils.go
k8s/migration/pkg/utils/maintenance_mode.go
k8s/migration/pkg/utils/rollingmigrationutils.go
k8s/migration/pkg/utils/types.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go
k8s/migration/pkg/utils/vmwareutils.go
ui/src/features/migration/RollingMigrationForm.tsx
ui/src/features/migration/useClusterData.ts

fixes #554 
This pull request enhances the rolling migration plan workflow by adding new migration phases for better status tracking and implementing improved validation checks for plan transitions. It also introduces utility functions for managing Openstack credentials, maintenance mode operations, and VMware host filtering to improve migration reliability and robustness.
</div>

rolling conversion validations

---

CONTRIBUTING.md
README.md

Nit: readme

---

.github/workflows/packer.yml
Makefile

fixes #711
This PR streamlines the build process by updating Makefile commands, eliminating redundant docker push operations and implementing focused docker build commands. The changes target multiple build triggers including ui, v2v-helper, vjail-controller, and build-vpwned, enhancing CI workflow efficiency in cross fork scenarios.
</div>

GH actions for cross fork PRs

---

.github/workflows/packer.yml

remove docker login for build only steps

---

k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/vmwarecreds_controller.go
k8s/migration/pkg/utils/credutils.go

fixes #555 
This PR updates container image pull policies for SSO initialization and revamps VMware credential handling while enhancing the migration module with proper synchronization for VM processing routines using wait groups. It ensures all concurrent VM operations complete before error reporting, improving system reliability and addressing issue #555. The changes aim to enhance performance and maintainability by refactoring legacy approaches and streamlining critical operations.
</div>

process single VM at a time

---

.github/workflows/packer.yml
Makefile
image_builder/configs/vjailbreak-settings.yaml
k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/credutils.go
v2v-helper/migrate/migrate.go
v2v-helper/pkg/constants/constants.go
v2v-helper/pkg/k8sutils/k8sutils.go
v2v-helper/pkg/utils/types.go
v2v-helper/pkg/utils/utils.go
v2v-helper/pkg/utils/vcenterutils.go
v2v-helper/vm/vmops.go

fixes #743 
This pull request introduces configurable vjailbreak settings via Kubernetes configmaps, standardizes error handling by replacing fmt.Errorf with errors.Wrap, and improves namespace references across packages. These changes enhance configuration management, error traceability, and overall system robustness for VM migration processes.
</div>

configurable vjb settings (release)

---

k8s/migration/pkg/utils/credutils.go
k8s/migration/pkg/utils/metadata_utils.go
v2v-helper/main.go
v2v-helper/pkg/utils/vcenterutils.go

fixes #774 
This pull request enhances OpenStack credentials validation and security groups configuration. It improves environment validation processes and error messaging while ensuring proper handling of security groups. The changes fix credential mismatches and strengthen migration reliability in cloud environments.
</div>

v0.3.0 fixes for SG and os creds validation

---

ui/src/features/migration/useClusterData.ts
ui/src/pages/dashboard/ClusterMigrationsTable.tsx
ui/src/pages/dashboard/MigrationsTable.tsx
ui/src/pages/dashboard/RollingMigrationsTable.tsx
ui/src/utils.ts

fixes #
This PR fixes time elapsed display issues across dashboard migration tables by updating components to pass row.status to the calculateTimeElapsed function. These changes ensure accurate time representation for both running and completed migrations, improving consistency throughout the application.
</div>

Fix time elapsed issue also 

---

v2v-helper/migrate/migrate.go
v2v-helper/migrate/migrate_test.go
v2v-helper/openstack/openstackops.go
v2v-helper/openstack/openstackops_mock.go
v2v-helper/pkg/utils/migrateutils/openstackopsutils.go
v2v-helper/virtv2v/virtv2vops_mock.go
v2v-helper/vm/vmops_mock.go

fixes #
This PR fixes a critical VM active wait timeout bug and enhances VM creation function signatures by adding vjailbreakSettings parameter. It improves error handling and execution flow during migration, while also updating test mocks to maintain API consistency. These changes result in more reliable VM provisioning and improved test simulation.
</div>

fix for wait active timeout

---

docs/src/content/docs/reference/compatibility.md

updated os compatibility table

---

pkg/vpwned/server/version.go
ui/src/components/UpgradeModal.tsx

fixes #
This pull request enhances server-side deletion logic by replacing fixed delays with dynamic polling and adding robust error handling for resource operations. The UI improvements introduce cleanup state management and display alerts during upgrades to prevent accidental interruptions, collectively improving system reliability during critical upgrade scenarios.
</div>

added alert in the ui while upgrade in progress

---

v2v-helper/migrate/migrate.go

fixes #825 
This pull request refines OS compatibility checks with improved log messages, enhances Windows bootable volume detection, and addresses issue #825 by improving error handling for Windows LDM environments. The changes improve compatibility verification and enhance user experience with better error handling for Windows LDM environments.
</div>

get bootable index for windows LDM

---

v2v-helper/openstack/openstackops.go
v2v-helper/pkg/utils/migrateutils/openstackopsutils.go

fixes #
This PR enhances system observability by implementing logging for all OpenStack API calls. It adds new authentication and tenant configuration parameters to the OpenStack client setup. The changes improve debugging capabilities across volume handling, network operations, and resource management functions.
</div>

logs all openstack calls that we make

---

docs/src/content/docs/guides/CLI-API/migrating_rdm_disk_windows_cluster_machine_using_cli.md

added title in rdm md file

---

image_builder/scripts/install.sh

fixes #977 
This pull request implements a default password mechanism for the ubuntu user in the installation script, configures SSH to enable password authentication, and forces password change on first login. These changes aim to enhance security by ensuring users update their credentials upon initial access.
</div>

Add a default password for Ubuntu user that needs to be changed on first boot
