platform9/vjailbreak

appliance/.gitignore
appliance/Makefile
appliance/README.md
appliance/Vagrantfile

This adds a Vagrant VM using flatcar linux and installs k3s on it. It will allow us to locally develop the k8s service components.
Closes https://github.com/platform9/vjailbreak/issues/2

Adds Vagrant VM for local development

---

k8s/migration/api/v1alpha1/migrationplan_types.go
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_migrationplans.yaml
k8s/migration/config/manager/manager.yaml
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/vmwarecreds_controller.go
v2v-helper/main.go
v2v-helper/migrate/migrate.go
v2v-helper/migrate/migrate_test.go
v2v-helper/nbd/nbdops.go
v2v-helper/nbd/nbdops_mock.go
v2v-helper/openstack/openstackops.go
v2v-helper/vcenter/vcenterops.go
v2v-helper/virtv2v/virtv2vops.go
v2v-helper/virtv2v/virtv2vops_mock.go

Close #39 
Retries one failed migration in the migration plan once. Changes retry field from true to false when it does this. If you wish to retry another failed migration in the same plan, you must set retry to true again manually.

Retry a failed migration in migrationplan

---

Makefile
deploy/00crds.yaml
k8s/migration/api/v1alpha1/migrationtemplate_types.go
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_migrationtemplates.yaml
k8s/migration/config/manager/manager.yaml
k8s/migration/internal/controller/vmwarecreds_controller.go
v2v-helper/migrate/migrate.go
v2v-helper/virtv2v/virtv2vops.go

- Adding IpAddress and VM state info to migrationtemplate status
- Adding helper make targets
- Resolving need to scale-down and scale-up controller manager deployment every time a new image is created. Done by setting `leader-election` to `false` which was anyway ineffective since we have only one replica
#132

add IpAddress and VM state info to migrationtemplate status

---

ui/src/api/migration-templates/migrationTemplates.ts
ui/src/api/migration-templates/model.ts
ui/src/constants.ts
ui/src/features/migration/MigrationForm.tsx
ui/src/features/migration/VmsSelectionStep.tsx

https://github.com/user-attachments/assets/91402e24-2e85-44a2-9cd4-553829817fcb
Changes ->
1. Make the dummy PATCH call for the migration template to trigger reconciliation in order to get latest VM details on manual refresh.
2. Added a 20-second forced timeout for every manual refresh, as it takes time for the latest VM details to reflect.
3. Disabled migration with a tooltip informing user to refresh, if the VM does not have an IP.

141 UI handle vm refresh with additional put call to migration template and addadjust the timeout needed for it to reflect latest detail

---

.github/workflows/packer.yml

- Fix GH workflow runs on release event add these events
```
- published
- edited
- released
- updated
```
- allow manual workflow runs

Fix GH workflow runs on release event

---

deploy/00crds.yaml
k8s/migration/api/v1alpha1/vjailbreaknode_types.go
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_vjailbreaknodes.yaml
k8s/migration/config/manager/kustomization.yaml
ui/src/api/nodes/model.ts
ui/src/pages/dashboard/ScaleUpDrawer.tsx

Make manifest and make build-installer

---

k8s/migration/internal/controller/openstackcreds_controller.go

Currently, the check passes even when there is a failure to get certificate from the endpoint. This is due to a typo in error check, we end up checking for wrong err variable.
Because of it ends up with a nil pointer dereference panic in GetOpenstackInfo when it is called by migration controller to get details of volume etc.
Test plan:
1. Built a new controller image.
2. Uploaded a OpenStack RC file with HTTP auth URL and without OS_INSECURE.
3. The validation failed as expected.
Fixes https://github.com/platform9/vjailbreak/issues/234

Fix panic caused by OpenstackCreds CA cert check

---

v2v-helper/main.go
v2v-helper/vm/vmops.go

Fixes #299 
This PR implements rollback support for failed VM migrations by adding VM power-on recovery functionality. The changes include updating the main application to trigger recovery steps and refining error messages. A new VMPowerOn function verifies and corrects VM power states when necessary, improving system resilience during failures.
<br>
<br>
<br>
<br>
</div>

Support rollback for failed VM

---

k8s/migration/internal/controller/migration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/pkg/constants/constants.go
v2v-helper/main.go

Fixes # 
This PR fixes a bug in the migration controller by properly assigning pod references, which resolves erratic migration status behavior. It enhances logging with updated context loggers and standardized error messages, introduces a new constant for consistent naming, and improves clarity in migration plan controller and v2v helper modules.
<br>
<br>
<br>
<br>
</div>

fix migration status with random pod ref name

---

.github/workflows/01_update_release_notes.yaml
.github/workflows/deploy_gh_page.yaml

Fixes # 
This PR updates two GitHub workflow files: modifying the release notes workflow to reference the correct documentation file extension and upgrading the Astro action to version 4 in the deployment workflow. These changes enhance documentation reliability and improve the deployment process.
<br>
<br>
<br>
<br>
</div>

update astro action to use v4

---

k8s/migration/pkg/utils/vjailbreaknodeutils.go

Fixes #233 
This PR fixes a bug in vjailbreaknode's volume boot process by replacing an error-prone image ID retrieval method with a robust OpenStack blockstorage function call. The implementation includes new imports, modified logic, and enhanced error handling to ensure accurate image ID retrieval, improving backend reliability.
<br>
<br>
<br>
<br>
</div>

Backend: Fix when we boot up vjailbreaknode from a volume 

---

ui/src/api/helpers.ts
ui/src/api/secrets/secrets.ts

UI shouldn't delete the secret, when we delete the creds respective secrets must be deleted by the backend itself.
Fixes #301 
This PR removes UI-based secret deletion logic from VMware and OpenStack credential deletion flows by removing outdated deletion calls from helper and secrets modules. The changes eliminate code that fetched credentials and conditionally deleted secrets, centralizing secret management exclusively in the backend instead of the UI, promoting more secure and consistent behavior.
<br>
<br>
<br> …

UI: Delete secret call

---

README.md
docs/astro.config.mjs
docs/src/content/docs/index.mdx

The updated URL to the actual getting started page instead of the landing page
This pull request updates documentation and configuration files to reflect new branding and correct navigation. The astro.config.mjs file now uses an SVG logo instead of a JPEG, aligning with the updated platform9 identity. Additionally, a redirection script has been added to the documentation index to guide users to the actual 'Getting Started' page.
<br>
<br>
<br>
<br>
</div>

Update the readme to point to the 'Getting Started'

---

k8s/migration/internal/controller/vmwarecreds_controller.go
k8s/migration/pkg/utils/credutils.go

Fixes #
This pull request optimizes VMware machine creation by implementing concurrent processing with Go's sync.WaitGroup, handling VMs in batches of 100 simultaneously. The implementation includes panic recovery and error logging in goroutines, with strategic wg.Wait calls to ensure completion before progression, significantly improving system efficiency.
<br>
<br>
<br>
<br>
</div>

 ( release ) Create vmwaremachines batch wise of 100 parallely. 

---

k8s/migration/internal/controller/openstackcreds_controller.go
k8s/migration/internal/controller/vmwarecreds_controller.go
k8s/migration/pkg/scope/vmwarecredsscope.go
k8s/migration/pkg/utils/credutils.go

Fixes # 
This PR enhances controller functionality by updating both OpenstackCreds and VMwareCreds controllers with improved context-aware scope closure behavior and error handling. It standardizes the code by updating function signatures, removing unnecessary context parameters, eliminating redundant finalizer addition, and adding deferred blocks for scope closure error management, resulting in more reliable and clearer controller logic.
<br>
<br>
<br>
<br> …

backend: close scope in vmware creds controller 

---

image_builder/configs/daemonset.yaml
image_builder/configs/env
image_builder/scripts/install.sh
image_builder/vjailbreak-image.pkr.hcl
k8s/migration/internal/controller/migrationplan_controller.go

Fixes #
From now on for any env which needs to be injected to v2v helper pod, can be done via this.  user is expected to populate /etc/pf9/env via cloud-init, and the script creates a config-map. In case later the user wants to add some env, he would have to recreate the configmap with the updated values.  
This pull request enables proxy environment variable injection via a configmap by enhancing multiple components. The daemonset configuration, install script, and packer build file have been updated to support the new environment injection …

Proxy env injection via configmap

---

docs/astro.config.mjs
docs/src/content/docs/guides/injecting_custom_env.md
k8s/migration/internal/controller/migrationplan_controller.go

Fixes # 
This pull request introduces a feature to inject environment variables into the v2v-helper pod through a dedicated env file and updated configuration scripts. It enhances credentials handling by requiring and validating datacenter fields, while improving overall configuration management and strengthening the migration credentials process.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>

Doc: Inject any environment variables required by user into v2v-helper pod. 

---

image_builder/configs/daemonset.yaml

Fixes #373
root@vjail-break:/home/ubuntu# ls -lrt
total 72928
-rwx------ 1 root   root      11913 Apr 10 06:58 get_helm.sh
-rw-r--r-- 1 ubuntu ubuntu 74646016 Apr 10 15:05 vmware-vix-disklib-distrib.tar
-rw-r--r-- 1 root   root       5051 Apr 22 04:49 script.sh
-rw-r--r-- 1 root   root       2966 Apr 22 05:30 daemonset.yaml
drwxr-xr-x 2 ubuntu ubuntu     4096 Apr 22 05:31 vmware-vix-disklib-distrib
directory is getting created and owner is ubuntu 
This PR enhances daemonset configuration by adding an init container that fixes file ownership issues …

Backend: Change ownership of /home/ubuntu/vmware-vix-disklib-distrib to ubuntu:ubuntu via init container. 

---

docs/astro.config.mjs
docs/src/content/docs/guides/injecting_custom_env.md
docs/src/content/docs/guides/scaling.md
docs/src/content/docs/guides/troubleshooting.md
docs/src/content/docs/introduction/components.md
docs/src/content/docs/introduction/getting_started.mdx
image_builder/configs/daemonset.yaml
image_builder/configs/env
image_builder/scripts/install.sh
image_builder/vjailbreak-image.pkr.hcl
k8s/migration/config/manager/manager.yaml
k8s/migration/go.sum
k8s/migration/internal/controller/migration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/pkg/utils/credutils.go
k8s/migration/pkg/utils/migrationutils.go
ui/src/components/drawers/OpenstackCredentialsDrawer.tsx
ui/src/features/migration/NetworkAndStorageMappingStep.tsx
v2v-helper/main.go

Fixes # 
This PR (v0.1.9) fixes critical bugs in deployment configurations and migration controllers while enhancing documentation clarity. It adds commands for proper directory permissions, improves migration controllers by filtering irrelevant conditions, removes forced migration phase updates, and optimizes credential utilities. It also introduces new containers and file provisioning while improving error handling across UI components and migration workflows.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, …

release v0.1.9

---

v2v-helper/migrate/migrate.go

**What this PR does / why we need it**: added counter output for incremental copy
Fixes #85 
This PR enhances the logging mechanism in the migration process by adding a counter output for incremental block copying in 'v2v-helper/migrate/migrate.go'. This improvement provides better visibility into migration progress and strengthens the system's diagnostic capabilities during block copy operations.
<br>
<br>
<br>
<br>
</div>

counter output for incremental copy

---

v2v-helper/migrate/migrate.go
v2v-helper/pkg/utils/openstackopsutils.go

Fixes #220 
This PR enhances error handling in network operations by adding nil network checks in the migration file and verifying subnet existence in OpenStack operations. These improvements prevent potential panics and provide clearer error messages, ultimately increasing the robustness of network-related functionalities.
<br>
<br>
<br>
<br>
</div>

v2v-helper: Add check if subnet exists to avoid panic. 

---

v2v-helper/openstack/openstackops.go

Fixes #455 
This PR enables re-authentication in OpenStack operations by setting the opts.AllowReauth flag to true. The change improves client resilience during transient failures by allowing automatic reauthentication. It maintains consistent error handling while enhancing operational stability, addressing issue #455.
<br>
<br>
<br>
<br>
</div>

enable openstack re-auth

---

v2v-helper/vm/vmops.go
v2v-helper/vm/vmops_mock.go

Fixes #412 
This PR implements a graceful guest OS shutdown mechanism before VM power-off, with timeout and fallback to forced shutdown. The implementation includes VMGuestShutdown function that checks power state, initiates shutdown, and waits for completion. Mock implementations were updated to support unit testing of the new functionality.
<br>
<br>
<b>Unit tests added</b>: True
<br>
<br>
</div>

do a guest shutdown before VM is powered off

---

.gitignore
k8s/migration/internal/controller/bmconfig_controller.go
k8s/migration/internal/controller/vmwarecreds_controller.go
v2v-helper/vm/vmops.go
v2v-helper/vm/vmops_mock.go

fixes #412 
This PR enhances error handling in BMConfig and VMwareCreds controllers while adding a new VMGuestShutdown feature for graceful VM shutdowns with power-off fallback. The changes improve error reporting clarity during status updates and include mock module updates to support comprehensive testing of the new functionality.
<br>
<br>
<b>Unit tests added</b>: True
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>

guest shutdown before power off

---

deploy/00crds.yaml
image_builder/configs/rsyncd.conf
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_migrations.yaml
k8s/migration/config/manager/kustomization.yaml
k8s/migration/internal/controller/migrationplan_controller.go
v2v-helper/main.go
v2v-helper/migrate/migrate.go
v2v-helper/nbd/nbdops.go
v2v-helper/pkg/constants/constants.go
v2v-helper/pkg/utils/nbdutils.go
v2v-helper/pkg/utils/openstackopsutils.go
v2v-helper/pkg/utils/utils.go
v2v-helper/reporter/reporter.go

Fixes #444
Fixes #396
Fixes #96
Fixes #111 
This PR enhances migration debugging capabilities by implementing consistent logging utilities at '/var/log/pf9' and updating container image configurations. It refactors modules to use a unified PrintLog mechanism while changing image registry and pull policies to ensure correct controller versions, improving log consistency and configuration stability.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 5
</div>

save migration debug logs at hostPath '/var/log/pf9' ( release )

---

ui/src/pages/dashboard/MigrationsTable.tsx

…of the migration
Fixes #447  
The pull request fixes a bug in the migration deletion workflow by modifying the deletion button's behavior and tooltip messaging. It also removes unnecessary code for row selection, simplifying the UI logic and allowing deletion in any migration state.
<br>
<br>
<br>
<br>
</div>

User should be able to delete migration when in pending or any stage

---

v2v-helper/Dockerfile
v2v-helper/migrate/migrate.go
v2v-helper/pkg/constants/constants.go
v2v-helper/pkg/utils/openstackopsutils.go

Fixes #
Previously, if a volume was still attached from a prior operation, the function would exit early when encountering "already attached". This led to cases where:
A DetachVolume call was still being processed.
A subsequent AttachVolumeToVM would assume attachment was complete, but in reality, it wasn't initiated by the current operation.
This caused timing issues where the attach logic would falsely succeed without guaranteeing the intended outcome. 
This PR enhances error handling and retry logic in …

Add check from nova side also for volume dettach 

---

v2v-helper/pkg/utils/openstackopsutils.go

Fixes # 
This PR extends the timeout duration for server activation in OpenStack operations, preventing premature timeouts while waiting for VMs to become active. The change improves system reliability by ensuring adequate wait time for server readiness, addressing a specific issue with VM activation timing.
</div>

Increase timeout for vm status to become active

---

k8s/migration/internal/controller/migrationplan_controller.go

Fixes # 
This PR optimizes resource management in the migration plan controller by modifying image pull policy and adjusting ephemeral storage settings. These targeted changes aim to save disk space on vjb VM while ensuring optimal performance and stability during container initialization and migration processes.
</div>

save disk space on vjb VM

---

deploy/00crds.yaml
k8s/migration/config/manager/manager.yaml

If we want to trigger force reconciliation of controller pods, right now, we need to scale down the deployment to 0 replicas and then scale up to 1 for it to work (this was due to a bug which caused new pod to never go into Running). This is tedious and time consuming. This PR resolves that bug
Fixes # 
This PR enhances Kubernetes manager configuration by implementing a preStop lifecycle hook and adjusting termination grace periods to fix migration-controller-manager pod deletion issues. These changes …

make delete migration-controller-manager pod work

---

image_builder/configs/daemonset.yaml
image_builder/scripts/download_images.sh

Fixes # 
This pull request updates image references to use a custom Alpine image from quay.io instead of docker.io in both deployment configurations and the download script. The changes streamline image sourcing across the codebase while removing some explicit package installations and adding a TODO for repository creation.
</div>

Add alpine docker image with rsync,coreutils in quay 

---

v2v-helper/Dockerfile

This PR uses the assets in the assets directory to install and version lock virt-v2v to 2.7.13 as that is the most tested version with vJailbreak.
Fixes #594 
This PR updates the v2v helper Dockerfile to use the assets library for package installation, streamlining the dependency process. It adds instructions to download the virt-v2v RPM and replaces old dependencies with direct installation commands, enhancing VM migration support and build reliability.
</div>

Use our assets library to build v2v helper

---

Makefile

Fixes # 
The pull request updates image variable definitions in the Makefile to include the REGISTRY prefix, supporting migration from cloud-ctl to pcdctl. These modifications streamline configuration and improve consistency in container deployments while aligning with the new tool transition.
</div>

change from cloud-ctl to pcdctl

---

image_builder/vjailbreak-image.pkr.hcl
v2v-helper/Dockerfile
v2v-helper/virtv2v/virtv2vops.go

Fixes # 
This PR updates the v2v-helper Dockerfile by replacing the Fedora base image with a newer version, adding build arguments for multi-platform builds, and implementing a multi-stage build process. It refreshes the ISO checksum in the image builder file, removes unnecessary repository additions, and enhances logging in virtv2vops.go with a '-v' flag for improved verbosity. These changes enhance image integrity and streamline container build workflows.
</div>

Change the base ubuntu image for vJailbreak qcow

---

deploy/00crds.yaml
k8s/migration/api/v1alpha1/migrationtemplate_types.go
k8s/migration/config/crd/bases/vjailbreak.k8s.pf9.io_migrationtemplates.yaml
k8s/migration/internal/controller/migrationplan_controller.go
ui/src/features/migration/constants.ts

Fixes # 
This PR enhances the migration plan controller by prioritizing the OS family configuration from migrationtemplate.Spec.OSFamily over vmMachine.Spec.VMInfo when available. The implementation adds conditional logic to ensure proper OS configuration during ConfigMap creation and includes appropriate error logging, improving overall system reliability.
</div>

accept os_family correctly and override if present

---

k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/pcdutils.go
v2v-helper/pkg/constants/constants.go
v2v-helper/pkg/utils/openstackopsutils.go

Fixes #609 
This PR implements support for clusterless migration on PCD by adding new constants and utilities for handling scenarios without a cluster. It introduces a function to create dummy clusters when needed, refines conditional logic in cluster management and openstack ops modules, and standardizes naming conventions across modules to address issue #609.
</div>

support migration without a cluster on pcd

---

v2v-helper/virtv2v/virtv2vops.go

fixes #613 
This PR improves error handling in virtv2v operations by fixing newline formatting in 'inspect-os' and 'lvs' commands and enhancing partition string parsing with proper trimming. These changes deliver cleaner error reporting and more consistent command output handling, directly addressing issue #613.
</div>

fix part-to-dev input

---

ui/src/components/forms/OpenstackRCFileUpload.tsx

Updates the OpenStack RC file parsing logic to correctly handle passwords containing the # (hash) character. With this change, passwords containing # are now accepted and validated without error.
Fixes #524 
This PR fixes incorrect parsing of OpenStack RC files containing special characters by implementing a custom line-by-line parser instead of using dotenv. It removes unnecessary debug logging, enhances the parser to handle special characters like '#' in credentials, and improves error handling by …

Fix RC file parsing to support special characters in OpenStack credentials.

---

.github/workflows/packer.yml
Makefile
deploy/00crds.yaml
image_builder/configs/version-config.yaml
image_builder/vjailbreak-image.pkr.hcl
k8s/migration/config/addons/kustomization.yaml
k8s/migration/config/manager/kustomization.yaml

Fixes # 
**Testing Done**
This PR introduces a ConfigMap-based version configuration feature by updating the image builder configuration and removing the version-config.yaml file move command. Changes include modifications to the Makefile while maintaining the overall file structure. YAML and kustomization files have been updated with current image tags to streamline manifest generation and improve deployment consistency.
</div>

configmap for current vjailbreak version (release)

---

k8s/migration/internal/controller/clustermigration_controller.go
k8s/migration/pkg/utils/credutils.go

fixes #
This PR modifies the cluster migration controller to trigger VM migrations when at least one ESXi migration succeeds, rather than requiring more than one. It also fixes an issue by replacing a generic string check with a specific prefix check in credential utilities to properly exclude vCLS VMs, enhancing overall migration reliability and efficiency.
</div>

Backport: vPwned: fix condition trigger for vm migrations

---

k8s/kube-prometheus/manifests/grafana-dashboardDefinitions.yaml
k8s/kube-prometheus/manifests/grafana-dashboardSources.yaml
k8s/kube-prometheus/manifests/grafana-deployment.yaml
k8s/kube-prometheus/manifests/grafana-folders.yaml

fixes #713 
fixed #103 
This pull request introduces a comprehensive Grafana dashboard for Kubernetes monitoring, featuring multiple panels for CPU, memory, network, and pod metrics. The dashboard enhances observability with various visualization settings including graphs, bar gauges, and tables. It addresses issue #713 and improves overall cluster performance monitoring capabilities.
</div>

add kubernetes dashboard by default to grafana

---

v2v-helper/migrate/migrate.go
v2v-helper/virtv2v/virtv2vops.go

Log time taken for operations like full copy, incremental copy, and total conversion using time.Now(). Helps benchmark and analyze migration performance over time.
fixes: https://github.com/platform9/vjailbreak/issues/513
Testing done
-  Performed a live migration of a VM.
- Verified that the VM was successfully migrated.
- Checked v2v-helper logs to confirm expected log messages were printed. Confirmed durations were logged for full copy, each incremental copy, and total conversion of a disk.
This PR enhances migration processes by adding detailed time tracking for disk and block copy operations. It implements duration logging for key migration steps in migrate.go and performance measurement …

v2v-helper: log time taken by disk copy and conversion

---

k8s/migration/internal/controller/esximigration_controller.go
k8s/migration/internal/controller/migration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/internal/controller/openstackcreds_controller.go
k8s/migration/internal/controller/rollingmigrationplan_controller.go
k8s/migration/internal/controller/vmwarecreds_controller.go
k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/bmprovisionerutils.go
k8s/migration/pkg/utils/credutils.go
k8s/migration/pkg/utils/migrationplanutils.go
k8s/migration/pkg/utils/pcdutils.go
k8s/migration/pkg/utils/rollingmigrationutils.go
k8s/migration/pkg/utils/vjailbreaknodeutils.go
k8s/migration/pkg/utils/vmwareutils.go
ui/src/features/migration/RollingMigrationForm.tsx

fixes #696 
This pull request implements fixes to enable vCenter operations in environments without clusters by correcting credential retrieval and host information functions. The changes standardize naming conventions for VMware and Openstack resources, enhance error handling, and introduce dummy cluster support for standalone ESXi environments. It removes outdated code and consolidates error pathways for clearer feedback when retrieving credentials and migration objects.
</div>

unblock vcenter with no clusters

---

ui/src/features/migration/useClusterData.ts

fixes #
This pull request fixes a UI issue in the migration feature by updating the property used to retrieve cluster names. The change switches from cluster.metadata.name to cluster.spec.name to align with the actual data schema, improving the reliability of cluster representation in the interface.
</div>

fix ui for clusters

---

v2v-helper/main.go
v2v-helper/vcenter/vcenterops.go

fixes #
This pull request addresses idle connection management issues in the vCenter integration components by modifying two key files. In main.go, a deferred function call has been added to close idle connections, ensuring resources are released properly. Additionally, in vcenterops.go, the KeepAlive duration is extended to improve connection stability.
</div>

idle connection timeout for vcenter

---

ui/src/features/migration/SourceDestinationClusterSelection.tsx
ui/src/features/migration/useClusterData.ts

fixes #
This PR reverts to using metadata-dependent display names for clusters in the migration feature. It updates UI components and cluster data mapping to ensure correct display properties. Type definitions and rendering logic were adjusted to provide more consistent and reliable cluster information display throughout the application.
</div>

revert back to metadata name

---

v2v-helper/pkg/utils/migrateutils/openstackopsutils.go

fixes #796 
This pull request reintroduces a DHCP fallback mechanism for port creation when static IP assignment fails. The implementation in openstackopsutils.go improves error handling by attempting DHCP port creation as a fallback strategy, with enhanced logging to track the process. These changes improve the overall robustness and reliability of network port assignment, particularly in non-matching subnet scenarios.
</div>

bring back dhcp for non-matching subnets

---

v2v-helper/migrate/migrate.go
v2v-helper/vcenter/vcenterops.go
v2v-helper/vm/vmops.go

fixes #784 
Field tested
This pull request addresses critical issues across migration, VCenter, and VM management modules by fixing VM session handling, ensuring fresh VM references for re-authentication, standardizing error messaging, and improving reliability of VM operations. The changes support new govomi client requirements by updating import statements and introducing property collector initialization while avoiding stale VM references.
</div>

fix vm refresh for new govomi clients

---

v2v-helper/migrate/migrate.go

fixes #
This PR fixes an error message in the migrate.go file by replacing the incorrect reference to migobj.VmwaremachineName with vminfo.Name. The correction improves error reporting clarity when TargetFlavorId is missing during flavorless creation, ensuring users receive proper information about configuration requirements.
</div>

indicate missing base flavor for specific vmwaremachine

---

k8s/migration/internal/controller/migration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/pkg/utils/migrationutils.go
ui/package-lock.json
ui/src/api/migrations/migrations.ts
ui/src/features/migration/VmsSelectionStep.tsx
ui/src/pages/dashboard/MigrationsTable.tsx
ui/yarn.lock

fixes #
This pull request addresses a critical bug in the migration process where the InitiateCutover boolean logic was inverted and cutover labels were incorrectly reset. The changes refactor the migration update process by directly patching migration objects instead of pods, update core controllers and utility functions, and revise the dashboard UI to accurately reflect admin cutover state. The PR also contains problematic dependency changes in yarn.lock that may affect macOS functionality.
</div>

Fix label getting triggered back to no, when patched

---

v2v-helper/vm/vmops.go

fixes #856 
This PR enhances CRD definitions by standardizing status configurations across migration plan YAML files. It fixes a bug in vmops.go by implementing case-insensitive MAC address comparison, preventing mismatches caused by letter casing differences. These changes improve system reliability and operational consistency.
</div>

equate mac id case insensitive

---

k8s/migration/internal/controller/migration_controller.go
k8s/migration/internal/controller/migrationplan_controller.go
k8s/migration/pkg/utils/credutils.go
v2v-helper/main.go
v2v-helper/migrate/migrate.go
v2v-helper/reporter/reporter.go

fixes #859 
All these were done using admin cutover. 
This pull request refines the migration process by addressing pod reference updates, admin cutover logic, and error reporting. It enhances the migration controller's logging and state handling, integrates a Reporter component for proper assessments, and prevents further disk copying when an admin cutover is initiated. The changes also include renaming functions, revising error conditions, and improving traceability for safer transitions. Additionally, it fixes a …

Fix admin cutover

---

k8s/migration/pkg/constants/constants.go
k8s/migration/pkg/utils/settings.go
v2v-helper/go.mod
v2v-helper/main.go
v2v-helper/openstack/openstackops.go
v2v-helper/pkg/constants/constants.go
v2v-helper/pkg/utils/migrateutils/openstackopsutils.go
v2v-helper/pkg/utils/types.go
v2v-helper/pkg/utils/utils.go

fixes #880 
This pull request enhances the configurability of volume wait intervals and retry limits by replacing hard-coded values with settings-driven parameters. New constants and settings have been introduced across the migration and utility modules to support dynamic configurations. The OpenStack operation flows have been refined by integrating the Kubernetes client and updating retry logic for volume operations.
</div>

volume wait interval through settings

---

v2v-helper/migrate/migrate.go

There is a situation where even though AdminCutOver option is selected, the VM gets powered off even before triggering cutOver.
This can happen when user has explicitly selected "cold" migration (power off live VM, then copy) in combination with AdminCutOver.
For cold migration, vjailbreak will power off the VM even before copy starts.
In such situation IMO we should assume that if "AdminCutOver" is selected, the expectation is "hot" migration (copy live VM, then power off)
In short, AdminCutOver takes precedence over "cold" migration
fixes #887  …

admin cut over poweroff sequence prevent user error

---

v2v-helper/migrate/migrate.go
v2v-helper/migrate/migrate_test.go

fixes #888 
This pull request refactors the migration code by introducing a new ReservePortsForVM function that centralizes port creation logic and modifies CreateTargetInstance to use these reserved ports. It removes redundant code and improves error handling for security group and network port management.
</div>

create openstack ports before copy

---

.github/workflows/deploy_gh_page.yaml

This PR removes the tags trigger from the docs deployment workflow. This prevents the workflow from incorrectly running and failing every time a new release is created.
fixes #936 
workflows ran on creating release before:
workflows ran on creating release after:
This PR updates the deployment workflow by changing the trigger from 'main' to 'gh-pages' branch and removing tag triggers. The changes aim to prevent workflow execution during releases, improving the stability of the automated release process and addressing configuration errors that caused failures.
</div>

disabled docs update workflow to run on release event

---

k8s/migration/pkg/utils/credutils.go

This PR adds owner references to RDM disk
fixes https://github.com/platform9/vjailbreak/issues/966
Deployed vjailbreak
1) Verified creds owner reference is added to rdm disk
2) Verified RDM disk is deleted if VmwareCreds is deleted
This pull request enhances RDM disk management by updating owner reference settings to properly link disks to VMwareCreds. The changes improve conditional checks for UID, Name, Kind, and APIVersion attributes, while refining error handling to provide more detailed feedback. This ensures RDM …

feat: Set owner reference for RDM disks to ensure proper deletion with VMwareCreds

---

k8s/migration/pkg/utils/credutils.go
pkg/vpwned/server/vjailbreak_proxy.go
ui/src/components/drawers/OpenstackCredentialsDrawer.tsx
ui/src/features/migration/RollingMigrationForm.tsx
v2v-helper/openstack/openstackops.go

Previously, OpenStack connections trusted any certificate the endpoint presented, while PCD required explicit insecure configuration. Trusting all certificates by default is inconsistent and insecure.
This change removes the default certificate trust logic and makes the behavior consistent with PCD: TLS verification is enforced unless OS_INSECURE is set. This had previously caused failures in PCD operations like fetching host. 
UI:
- Added "Allow insecure TLS" toggle in OpenStack credentials drawer.
- Toggle reads OS_INSECURE values from rc file and skips TLS verification accordingly.
- Allows working with insecure endpoints and self-signed certs.
Test plan:
- Launched UI with and without OS_INSECURE in rc file.
- Verified toggle sends OS_INSECURE=true in POST body when enabled.
- …

tls: remove cert trust logic, rely on OS_INSECURE for skipping verification

---

k8s/migration/pkg/utils/credutils.go

Change is to add disk name check before updating annotation reference to fix incorrect annotation updation when more than one RDM disk is in cluster 
fixes #983 
This PR enhances RDM disk information handling by adding disk name validation before updating volume references. It improves system robustness by ensuring only well-formatted volume references are accepted, while also enhancing logging and refining variables for better diagnostics.
</div>

feat: Enhance RDM disk info population by validating disk name before updating volume reference
